/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as SsoCallbackRouteImport } from './routes/sso-callback'
import { Route as SsoRouteImport } from './routes/sso'
import { Route as ResetPasswordRouteImport } from './routes/reset-password'
import { Route as LoginRouteImport } from './routes/login'
import { Route as CadastroRouteImport } from './routes/cadastro'
import { Route as AuthenticatedRouteImport } from './routes/_authenticated'
import { Route as AuthenticatedIndexRouteImport } from './routes/_authenticated/index'
import { Route as AuthConfirmRouteImport } from './routes/auth/confirm'
import { Route as AuthenticatedPerfilRouteImport } from './routes/_authenticated/perfil'
import { Route as AuthenticatedAdminRouteImport } from './routes/_authenticated/admin'
import { Route as AuthenticatedDemandasIndexRouteImport } from './routes/_authenticated/demandas.index'
import { Route as AuthenticatedDemandasNovaRouteImport } from './routes/_authenticated/demandas.nova'
import { Route as AuthenticatedDemandasKanbanRouteImport } from './routes/_authenticated/demandas.kanban'
import { Route as AuthenticatedDemandasExcluidasRouteImport } from './routes/_authenticated/demandas.excluidas'
import { Route as AuthenticatedDemandasCodigoRouteImport } from './routes/_authenticated/demandas.$codigo'
import { Route as AuthenticatedAdminUsuariosRouteImport } from './routes/_authenticated/admin/usuarios'
import { Route as AuthenticatedAdminTenantsRouteImport } from './routes/_authenticated/admin/tenants'
import { Route as AuthenticatedAdminSubmodulosRouteImport } from './routes/_authenticated/admin/submodulos'
import { Route as AuthenticatedAdminPerfisAcessoRouteImport } from './routes/_authenticated/admin/perfis-acesso'
import { Route as AuthenticatedAdminModulosRouteImport } from './routes/_authenticated/admin/modulos'
import { Route as AuthenticatedAdminAreasRouteImport } from './routes/_authenticated/admin/areas'

const SsoCallbackRoute = SsoCallbackRouteImport.update({
  id: '/sso-callback',
  path: '/sso-callback',
  getParentRoute: () => rootRouteImport,
} as any)
const SsoRoute = SsoRouteImport.update({
  id: '/sso',
  path: '/sso',
  getParentRoute: () => rootRouteImport,
} as any)
const ResetPasswordRoute = ResetPasswordRouteImport.update({
  id: '/reset-password',
  path: '/reset-password',
  getParentRoute: () => rootRouteImport,
} as any)
const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const CadastroRoute = CadastroRouteImport.update({
  id: '/cadastro',
  path: '/cadastro',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedRoute = AuthenticatedRouteImport.update({
  id: '/_authenticated',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedIndexRoute = AuthenticatedIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthConfirmRoute = AuthConfirmRouteImport.update({
  id: '/auth/confirm',
  path: '/auth/confirm',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthenticatedPerfilRoute = AuthenticatedPerfilRouteImport.update({
  id: '/perfil',
  path: '/perfil',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedAdminRoute = AuthenticatedAdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => AuthenticatedRoute,
} as any)
const AuthenticatedDemandasIndexRoute =
  AuthenticatedDemandasIndexRouteImport.update({
    id: '/demandas/',
    path: '/demandas/',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandasNovaRoute =
  AuthenticatedDemandasNovaRouteImport.update({
    id: '/demandas/nova',
    path: '/demandas/nova',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandasKanbanRoute =
  AuthenticatedDemandasKanbanRouteImport.update({
    id: '/demandas/kanban',
    path: '/demandas/kanban',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandasExcluidasRoute =
  AuthenticatedDemandasExcluidasRouteImport.update({
    id: '/demandas/excluidas',
    path: '/demandas/excluidas',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedDemandasCodigoRoute =
  AuthenticatedDemandasCodigoRouteImport.update({
    id: '/demandas/$codigo',
    path: '/demandas/$codigo',
    getParentRoute: () => AuthenticatedRoute,
  } as any)
const AuthenticatedAdminUsuariosRoute =
  AuthenticatedAdminUsuariosRouteImport.update({
    id: '/usuarios',
    path: '/usuarios',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminTenantsRoute =
  AuthenticatedAdminTenantsRouteImport.update({
    id: '/tenants',
    path: '/tenants',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminSubmodulosRoute =
  AuthenticatedAdminSubmodulosRouteImport.update({
    id: '/submodulos',
    path: '/submodulos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminPerfisAcessoRoute =
  AuthenticatedAdminPerfisAcessoRouteImport.update({
    id: '/perfis-acesso',
    path: '/perfis-acesso',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminModulosRoute =
  AuthenticatedAdminModulosRouteImport.update({
    id: '/modulos',
    path: '/modulos',
    getParentRoute: () => AuthenticatedAdminRoute,
  } as any)
const AuthenticatedAdminAreasRoute = AuthenticatedAdminAreasRouteImport.update({
  id: '/areas',
  path: '/areas',
  getParentRoute: () => AuthenticatedAdminRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof AuthenticatedIndexRoute
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sso': typeof SsoRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/perfis-acesso': typeof AuthenticatedAdminPerfisAcessoRoute
  '/admin/submodulos': typeof AuthenticatedAdminSubmodulosRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/demandas/$codigo': typeof AuthenticatedDemandasCodigoRoute
  '/demandas/excluidas': typeof AuthenticatedDemandasExcluidasRoute
  '/demandas/kanban': typeof AuthenticatedDemandasKanbanRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/demandas/': typeof AuthenticatedDemandasIndexRoute
}
export interface FileRoutesByTo {
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sso': typeof SsoRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/admin': typeof AuthenticatedAdminRouteWithChildren
  '/perfil': typeof AuthenticatedPerfilRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/': typeof AuthenticatedIndexRoute
  '/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/admin/perfis-acesso': typeof AuthenticatedAdminPerfisAcessoRoute
  '/admin/submodulos': typeof AuthenticatedAdminSubmodulosRoute
  '/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/demandas/$codigo': typeof AuthenticatedDemandasCodigoRoute
  '/demandas/excluidas': typeof AuthenticatedDemandasExcluidasRoute
  '/demandas/kanban': typeof AuthenticatedDemandasKanbanRoute
  '/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/demandas': typeof AuthenticatedDemandasIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/_authenticated': typeof AuthenticatedRouteWithChildren
  '/cadastro': typeof CadastroRoute
  '/login': typeof LoginRoute
  '/reset-password': typeof ResetPasswordRoute
  '/sso': typeof SsoRoute
  '/sso-callback': typeof SsoCallbackRoute
  '/_authenticated/admin': typeof AuthenticatedAdminRouteWithChildren
  '/_authenticated/perfil': typeof AuthenticatedPerfilRoute
  '/auth/confirm': typeof AuthConfirmRoute
  '/_authenticated/': typeof AuthenticatedIndexRoute
  '/_authenticated/admin/areas': typeof AuthenticatedAdminAreasRoute
  '/_authenticated/admin/modulos': typeof AuthenticatedAdminModulosRoute
  '/_authenticated/admin/perfis-acesso': typeof AuthenticatedAdminPerfisAcessoRoute
  '/_authenticated/admin/submodulos': typeof AuthenticatedAdminSubmodulosRoute
  '/_authenticated/admin/tenants': typeof AuthenticatedAdminTenantsRoute
  '/_authenticated/admin/usuarios': typeof AuthenticatedAdminUsuariosRoute
  '/_authenticated/demandas/$codigo': typeof AuthenticatedDemandasCodigoRoute
  '/_authenticated/demandas/excluidas': typeof AuthenticatedDemandasExcluidasRoute
  '/_authenticated/demandas/kanban': typeof AuthenticatedDemandasKanbanRoute
  '/_authenticated/demandas/nova': typeof AuthenticatedDemandasNovaRoute
  '/_authenticated/demandas/': typeof AuthenticatedDemandasIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/sso'
    | '/sso-callback'
    | '/admin'
    | '/perfil'
    | '/auth/confirm'
    | '/admin/areas'
    | '/admin/modulos'
    | '/admin/perfis-acesso'
    | '/admin/submodulos'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/demandas/$codigo'
    | '/demandas/excluidas'
    | '/demandas/kanban'
    | '/demandas/nova'
    | '/demandas/'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/sso'
    | '/sso-callback'
    | '/admin'
    | '/perfil'
    | '/auth/confirm'
    | '/'
    | '/admin/areas'
    | '/admin/modulos'
    | '/admin/perfis-acesso'
    | '/admin/submodulos'
    | '/admin/tenants'
    | '/admin/usuarios'
    | '/demandas/$codigo'
    | '/demandas/excluidas'
    | '/demandas/kanban'
    | '/demandas/nova'
    | '/demandas'
  id:
    | '__root__'
    | '/_authenticated'
    | '/cadastro'
    | '/login'
    | '/reset-password'
    | '/sso'
    | '/sso-callback'
    | '/_authenticated/admin'
    | '/_authenticated/perfil'
    | '/auth/confirm'
    | '/_authenticated/'
    | '/_authenticated/admin/areas'
    | '/_authenticated/admin/modulos'
    | '/_authenticated/admin/perfis-acesso'
    | '/_authenticated/admin/submodulos'
    | '/_authenticated/admin/tenants'
    | '/_authenticated/admin/usuarios'
    | '/_authenticated/demandas/$codigo'
    | '/_authenticated/demandas/excluidas'
    | '/_authenticated/demandas/kanban'
    | '/_authenticated/demandas/nova'
    | '/_authenticated/demandas/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  AuthenticatedRoute: typeof AuthenticatedRouteWithChildren
  CadastroRoute: typeof CadastroRoute
  LoginRoute: typeof LoginRoute
  ResetPasswordRoute: typeof ResetPasswordRoute
  SsoRoute: typeof SsoRoute
  SsoCallbackRoute: typeof SsoCallbackRoute
  AuthConfirmRoute: typeof AuthConfirmRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/sso-callback': {
      id: '/sso-callback'
      path: '/sso-callback'
      fullPath: '/sso-callback'
      preLoaderRoute: typeof SsoCallbackRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/sso': {
      id: '/sso'
      path: '/sso'
      fullPath: '/sso'
      preLoaderRoute: typeof SsoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/reset-password': {
      id: '/reset-password'
      path: '/reset-password'
      fullPath: '/reset-password'
      preLoaderRoute: typeof ResetPasswordRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cadastro': {
      id: '/cadastro'
      path: '/cadastro'
      fullPath: '/cadastro'
      preLoaderRoute: typeof CadastroRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated': {
      id: '/_authenticated'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/': {
      id: '/_authenticated/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthenticatedIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/auth/confirm': {
      id: '/auth/confirm'
      path: '/auth/confirm'
      fullPath: '/auth/confirm'
      preLoaderRoute: typeof AuthConfirmRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_authenticated/perfil': {
      id: '/_authenticated/perfil'
      path: '/perfil'
      fullPath: '/perfil'
      preLoaderRoute: typeof AuthenticatedPerfilRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin': {
      id: '/_authenticated/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AuthenticatedAdminRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas/': {
      id: '/_authenticated/demandas/'
      path: '/demandas'
      fullPath: '/demandas/'
      preLoaderRoute: typeof AuthenticatedDemandasIndexRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas/nova': {
      id: '/_authenticated/demandas/nova'
      path: '/demandas/nova'
      fullPath: '/demandas/nova'
      preLoaderRoute: typeof AuthenticatedDemandasNovaRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas/kanban': {
      id: '/_authenticated/demandas/kanban'
      path: '/demandas/kanban'
      fullPath: '/demandas/kanban'
      preLoaderRoute: typeof AuthenticatedDemandasKanbanRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas/excluidas': {
      id: '/_authenticated/demandas/excluidas'
      path: '/demandas/excluidas'
      fullPath: '/demandas/excluidas'
      preLoaderRoute: typeof AuthenticatedDemandasExcluidasRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/demandas/$codigo': {
      id: '/_authenticated/demandas/$codigo'
      path: '/demandas/$codigo'
      fullPath: '/demandas/$codigo'
      preLoaderRoute: typeof AuthenticatedDemandasCodigoRouteImport
      parentRoute: typeof AuthenticatedRoute
    }
    '/_authenticated/admin/usuarios': {
      id: '/_authenticated/admin/usuarios'
      path: '/usuarios'
      fullPath: '/admin/usuarios'
      preLoaderRoute: typeof AuthenticatedAdminUsuariosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/tenants': {
      id: '/_authenticated/admin/tenants'
      path: '/tenants'
      fullPath: '/admin/tenants'
      preLoaderRoute: typeof AuthenticatedAdminTenantsRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/submodulos': {
      id: '/_authenticated/admin/submodulos'
      path: '/submodulos'
      fullPath: '/admin/submodulos'
      preLoaderRoute: typeof AuthenticatedAdminSubmodulosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/perfis-acesso': {
      id: '/_authenticated/admin/perfis-acesso'
      path: '/perfis-acesso'
      fullPath: '/admin/perfis-acesso'
      preLoaderRoute: typeof AuthenticatedAdminPerfisAcessoRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/modulos': {
      id: '/_authenticated/admin/modulos'
      path: '/modulos'
      fullPath: '/admin/modulos'
      preLoaderRoute: typeof AuthenticatedAdminModulosRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
    '/_authenticated/admin/areas': {
      id: '/_authenticated/admin/areas'
      path: '/areas'
      fullPath: '/admin/areas'
      preLoaderRoute: typeof AuthenticatedAdminAreasRouteImport
      parentRoute: typeof AuthenticatedAdminRoute
    }
  }
}

interface AuthenticatedAdminRouteChildren {
  AuthenticatedAdminAreasRoute: typeof AuthenticatedAdminAreasRoute
  AuthenticatedAdminModulosRoute: typeof AuthenticatedAdminModulosRoute
  AuthenticatedAdminPerfisAcessoRoute: typeof AuthenticatedAdminPerfisAcessoRoute
  AuthenticatedAdminSubmodulosRoute: typeof AuthenticatedAdminSubmodulosRoute
  AuthenticatedAdminTenantsRoute: typeof AuthenticatedAdminTenantsRoute
  AuthenticatedAdminUsuariosRoute: typeof AuthenticatedAdminUsuariosRoute
}

const AuthenticatedAdminRouteChildren: AuthenticatedAdminRouteChildren = {
  AuthenticatedAdminAreasRoute: AuthenticatedAdminAreasRoute,
  AuthenticatedAdminModulosRoute: AuthenticatedAdminModulosRoute,
  AuthenticatedAdminPerfisAcessoRoute: AuthenticatedAdminPerfisAcessoRoute,
  AuthenticatedAdminSubmodulosRoute: AuthenticatedAdminSubmodulosRoute,
  AuthenticatedAdminTenantsRoute: AuthenticatedAdminTenantsRoute,
  AuthenticatedAdminUsuariosRoute: AuthenticatedAdminUsuariosRoute,
}

const AuthenticatedAdminRouteWithChildren =
  AuthenticatedAdminRoute._addFileChildren(AuthenticatedAdminRouteChildren)

interface AuthenticatedRouteChildren {
  AuthenticatedAdminRoute: typeof AuthenticatedAdminRouteWithChildren
  AuthenticatedPerfilRoute: typeof AuthenticatedPerfilRoute
  AuthenticatedIndexRoute: typeof AuthenticatedIndexRoute
  AuthenticatedDemandasCodigoRoute: typeof AuthenticatedDemandasCodigoRoute
  AuthenticatedDemandasExcluidasRoute: typeof AuthenticatedDemandasExcluidasRoute
  AuthenticatedDemandasKanbanRoute: typeof AuthenticatedDemandasKanbanRoute
  AuthenticatedDemandasNovaRoute: typeof AuthenticatedDemandasNovaRoute
  AuthenticatedDemandasIndexRoute: typeof AuthenticatedDemandasIndexRoute
}

const AuthenticatedRouteChildren: AuthenticatedRouteChildren = {
  AuthenticatedAdminRoute: AuthenticatedAdminRouteWithChildren,
  AuthenticatedPerfilRoute: AuthenticatedPerfilRoute,
  AuthenticatedIndexRoute: AuthenticatedIndexRoute,
  AuthenticatedDemandasCodigoRoute: AuthenticatedDemandasCodigoRoute,
  AuthenticatedDemandasExcluidasRoute: AuthenticatedDemandasExcluidasRoute,
  AuthenticatedDemandasKanbanRoute: AuthenticatedDemandasKanbanRoute,
  AuthenticatedDemandasNovaRoute: AuthenticatedDemandasNovaRoute,
  AuthenticatedDemandasIndexRoute: AuthenticatedDemandasIndexRoute,
}

const AuthenticatedRouteWithChildren = AuthenticatedRoute._addFileChildren(
  AuthenticatedRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  AuthenticatedRoute: AuthenticatedRouteWithChildren,
  CadastroRoute: CadastroRoute,
  LoginRoute: LoginRoute,
  ResetPasswordRoute: ResetPasswordRoute,
  SsoRoute: SsoRoute,
  SsoCallbackRoute: SsoCallbackRoute,
  AuthConfirmRoute: AuthConfirmRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
